version: '3'

services:
  laravel-app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: dockerfile  # Use the Dockerfile for Laravel
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gptWebsiteGenerator
      - DB_USERNAME=root
      - DB_PASSWORD=your_mysql_password  # Set your MySQL password here

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password  # Set your MySQL root password here
      MYSQL_DATABASE: gptWebsiteGenerator  # Your Laravel database name
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
